require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SportKeywordsController do

  # This should return the minimal set of attributes required to create a valid
  # SportKeyword. As you add validations to SportKeyword, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "rule_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SportKeywordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sport_keywords as @sport_keywords" do
      sport_keyword = SportKeyword.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sport_keywords).should eq([sport_keyword])
    end
  end

  describe "GET show" do
    it "assigns the requested sport_keyword as @sport_keyword" do
      sport_keyword = SportKeyword.create! valid_attributes
      get :show, {:id => sport_keyword.to_param}, valid_session
      assigns(:sport_keyword).should eq(sport_keyword)
    end
  end

  describe "GET new" do
    it "assigns a new sport_keyword as @sport_keyword" do
      get :new, {}, valid_session
      assigns(:sport_keyword).should be_a_new(SportKeyword)
    end
  end

  describe "GET edit" do
    it "assigns the requested sport_keyword as @sport_keyword" do
      sport_keyword = SportKeyword.create! valid_attributes
      get :edit, {:id => sport_keyword.to_param}, valid_session
      assigns(:sport_keyword).should eq(sport_keyword)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SportKeyword" do
        expect {
          post :create, {:sport_keyword => valid_attributes}, valid_session
        }.to change(SportKeyword, :count).by(1)
      end

      it "assigns a newly created sport_keyword as @sport_keyword" do
        post :create, {:sport_keyword => valid_attributes}, valid_session
        assigns(:sport_keyword).should be_a(SportKeyword)
        assigns(:sport_keyword).should be_persisted
      end

      it "redirects to the created sport_keyword" do
        post :create, {:sport_keyword => valid_attributes}, valid_session
        response.should redirect_to(SportKeyword.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sport_keyword as @sport_keyword" do
        # Trigger the behavior that occurs when invalid params are submitted
        SportKeyword.any_instance.stub(:save).and_return(false)
        post :create, {:sport_keyword => { "rule_type" => "invalid value" }}, valid_session
        assigns(:sport_keyword).should be_a_new(SportKeyword)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SportKeyword.any_instance.stub(:save).and_return(false)
        post :create, {:sport_keyword => { "rule_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sport_keyword" do
        sport_keyword = SportKeyword.create! valid_attributes
        # Assuming there are no other sport_keywords in the database, this
        # specifies that the SportKeyword created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SportKeyword.any_instance.should_receive(:update).with({ "rule_type" => "MyString" })
        put :update, {:id => sport_keyword.to_param, :sport_keyword => { "rule_type" => "MyString" }}, valid_session
      end

      it "assigns the requested sport_keyword as @sport_keyword" do
        sport_keyword = SportKeyword.create! valid_attributes
        put :update, {:id => sport_keyword.to_param, :sport_keyword => valid_attributes}, valid_session
        assigns(:sport_keyword).should eq(sport_keyword)
      end

      it "redirects to the sport_keyword" do
        sport_keyword = SportKeyword.create! valid_attributes
        put :update, {:id => sport_keyword.to_param, :sport_keyword => valid_attributes}, valid_session
        response.should redirect_to(sport_keyword)
      end
    end

    describe "with invalid params" do
      it "assigns the sport_keyword as @sport_keyword" do
        sport_keyword = SportKeyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SportKeyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => sport_keyword.to_param, :sport_keyword => { "rule_type" => "invalid value" }}, valid_session
        assigns(:sport_keyword).should eq(sport_keyword)
      end

      it "re-renders the 'edit' template" do
        sport_keyword = SportKeyword.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SportKeyword.any_instance.stub(:save).and_return(false)
        put :update, {:id => sport_keyword.to_param, :sport_keyword => { "rule_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sport_keyword" do
      sport_keyword = SportKeyword.create! valid_attributes
      expect {
        delete :destroy, {:id => sport_keyword.to_param}, valid_session
      }.to change(SportKeyword, :count).by(-1)
    end

    it "redirects to the sport_keywords list" do
      sport_keyword = SportKeyword.create! valid_attributes
      delete :destroy, {:id => sport_keyword.to_param}, valid_session
      response.should redirect_to(sport_keywords_url)
    end
  end

end
